### ISSUE TITLE
Error when use LSTM-CNN model.

### ISSUE THREAD

**Issue by zengliangju** [pmsosa/CS291K#3]
Here is the traceback :

```
Traceback (most recent call last):
  File "train.py", line 143, in <module>
    model = LSTM_CNN(x_train.shape[1],y_train.shape[1],len(vocab_processor.vocabulary_),embedding_dim,filter_sizes,num_filters,l2_reg_lambda)
  File "/home/bishe/Workspace/lstm_cnn_original/lstm_cnn.py", line 39, in __init__
    conv = tf.nn.conv2d(self.lstm_out_expanded, W,strides=[1, 1, 1, 1],padding="VALID",name="conv")
  File "/home/bishe/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 639, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/bishe/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/bishe/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3162, in create_op
    compute_device=compute_device)
  File "/home/bishe/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3208, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/home/bishe/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2427, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/home/bishe/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2400, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/bishe/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2330, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/bishe/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/bishe/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 50 from 32 for 'conv-maxpool-3/conv' (op: 'Conv2D') with input shapes: [?,50,32,1], [3,50,1,32].
```

What's wrong with it.

By the way, I use data in https://github.com/pmsosa/Twitter-Sentiment-Analysis/tree/master/data

**Comment by zengliangju** [comment]
I found the reason. The variable ```use_glove``` shuold be set as ```False``` in ```train.py```.
